# Generated by Django 4.2.5 on 2023-09-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pitcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=50)),
                ("wins", models.IntegerField()),
                ("losses", models.IntegerField()),
                ("saves", models.IntegerField()),
                ("games", models.IntegerField()),
                ("games_started", models.IntegerField()),
                (
                    "innings_pitched",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                ("k_per_9", models.DecimalField(decimal_places=2, max_digits=4)),
                ("bb_per_9", models.DecimalField(decimal_places=2, max_digits=4)),
                ("hr_per_9", models.DecimalField(decimal_places=2, max_digits=4)),
                ("babip", models.DecimalField(decimal_places=3, max_digits=5)),
                ("lob_percentage", models.DecimalField(decimal_places=1, max_digits=5)),
                ("gb_percentage", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "hr_fb_percentage",
                    models.DecimalField(decimal_places=1, max_digits=5),
                ),
                ("vfa", models.DecimalField(decimal_places=1, max_digits=5)),
                ("era", models.DecimalField(decimal_places=2, max_digits=4)),
                ("xera", models.DecimalField(decimal_places=2, max_digits=4)),
                ("fip", models.DecimalField(decimal_places=2, max_digits=4)),
                ("xfip", models.DecimalField(decimal_places=2, max_digits=4)),
                ("war", models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name="PositionPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("team", models.CharField(max_length=50)),
                ("games", models.IntegerField()),
                ("plate_appearances", models.IntegerField()),
                ("home_runs", models.IntegerField()),
                ("runs", models.IntegerField()),
                ("runs_batted_in", models.IntegerField()),
                ("stolen_bases", models.IntegerField()),
                (
                    "walk_percentage",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "strikeout_percentage",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("isolated_power", models.DecimalField(decimal_places=3, max_digits=5)),
                ("babip", models.DecimalField(decimal_places=3, max_digits=5)),
                ("avg", models.DecimalField(decimal_places=3, max_digits=5)),
                ("obp", models.DecimalField(decimal_places=3, max_digits=5)),
                ("slg", models.DecimalField(decimal_places=3, max_digits=5)),
                ("woba", models.DecimalField(decimal_places=3, max_digits=5)),
                ("xwoba", models.DecimalField(decimal_places=3, max_digits=5)),
                ("wrc_plus", models.IntegerField()),
                ("base_running", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "offensive_value",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "defensive_value",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("war", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
