# Generated by Django 4.2.5 on 2023-09-19 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pitcher",
            name="num",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="num",
        ),
    ]
