# Generated by Django 4.2.5 on 2024-01-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_remove_pitcher_num_remove_positionplayer_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitcher",
            name="efficiency_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="pitcher",
            name="net_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="pitcher",
            name="performance_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="positionplayer",
            name="defense_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="positionplayer",
            name="net_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="positionplayer",
            name="offense_rating",
            field=models.FloatField(default=0),
        ),
    ]
