# Generated by Django 4.2.5 on 2024-01-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0004_pitcher_efficiency_rating_percentile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitcher",
            name="war_last_year",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="pitcher",
            name="war_year_before_last",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="positionplayer",
            name="war_last_year",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="positionplayer",
            name="war_year_before_last",
            field=models.FloatField(default=0),
        ),
    ]
