# Generated by Django 4.2.5 on 2024-01-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0005_pitcher_war_last_year_pitcher_war_year_before_last_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitcher",
            name="predicted_war",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="positionplayer",
            name="predicted_war",
            field=models.FloatField(default=0),
        ),
    ]
