# Generated by Django 4.2.5 on 2024-01-23 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0006_pitcher_predicted_war_positionplayer_predicted_war"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pitcher",
            name="efficiency_rating",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="efficiency_rating_percentile",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="net_rating",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="net_rating_percentile",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="performance_rating",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="performance_rating_percentile",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="predicted_war",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="war_last_year",
        ),
        migrations.RemoveField(
            model_name="pitcher",
            name="war_year_before_last",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="defense_rating",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="defense_rating_percentile",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="net_rating",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="net_rating_percentile",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="offense_rating",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="offense_rating_percentile",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="predicted_war",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="war_last_year",
        ),
        migrations.RemoveField(
            model_name="positionplayer",
            name="war_year_before_last",
        ),
    ]
