from django.db import models

# Create your models here.
class PositionPlayer(models.Model):
    name = models.CharField(max_length=100)
    team = models.CharField(max_length=50)
    games = models.IntegerField()
    plate_appearances = models.IntegerField()
    home_runs = models.IntegerField()
    runs = models.IntegerField()
    runs_batted_in = models.IntegerField()
    stolen_bases = models.IntegerField()
    walk_percentage = models.DecimalField(max_digits=4, decimal_places=2)
    strikeout_percentage = models.DecimalField(max_digits=4, decimal_places=2)
    isolated_power = models.DecimalField(max_digits=5, decimal_places=3)
    babip = models.DecimalField(max_digits=5, decimal_places=3)
    avg = models.DecimalField(max_digits=5, decimal_places=3)
    obp = models.DecimalField(max_digits=5, decimal_places=3)
    slg = models.DecimalField(max_digits=5, decimal_places=3)
    woba = models.DecimalField(max_digits=5, decimal_places=3)
    xwoba = models.DecimalField(max_digits=5, decimal_places=3)
    wrc_plus = models.IntegerField()
    base_running = models.DecimalField(max_digits=5, decimal_places=2)
    offensive_value = models.DecimalField(max_digits=5, decimal_places=2)
    defensive_value = models.DecimalField(max_digits=5, decimal_places=2)
    war = models.DecimalField(max_digits=5, decimal_places=2)
    offense_rating = models.FloatField(default=0)
    defense_rating = models.FloatField(default=0)
    net_rating = models.FloatField(default=0)
    offense_rating_percentile = models.FloatField(default=0)
    defense_rating_percentile = models.FloatField(default=0)
    net_rating_percentile = models.FloatField(default=0)
    war_last_year = models.FloatField(default=0)
    war_year_before_last = models.FloatField(default=0)
    predicted_war = models.FloatField(default=0)
    

class Pitcher(models.Model):
    name = models.CharField(max_length=100)
    team = models.CharField(max_length=50)
    wins = models.IntegerField()
    losses = models.IntegerField()
    saves = models.IntegerField()
    games = models.IntegerField()
    games_started = models.IntegerField()
    innings_pitched = models.DecimalField(max_digits=5, decimal_places=1)
    k_per_9 = models.DecimalField(max_digits=4, decimal_places=2)
    bb_per_9 = models.DecimalField(max_digits=4, decimal_places=2)
    hr_per_9 = models.DecimalField(max_digits=4, decimal_places=2)
    babip = models.DecimalField(max_digits=5, decimal_places=3)
    lob_percentage = models.DecimalField(max_digits=5, decimal_places=1)
    gb_percentage = models.DecimalField(max_digits=5, decimal_places=1)
    hr_fb_percentage = models.DecimalField(max_digits=5, decimal_places=1)
    vfa = models.DecimalField(max_digits=5, decimal_places=1)
    era = models.DecimalField(max_digits=4, decimal_places=2)
    xera = models.DecimalField(max_digits=4, decimal_places=2)
    fip = models.DecimalField(max_digits=4, decimal_places=2)
    xfip = models.DecimalField(max_digits=4, decimal_places=2)
    war = models.DecimalField(max_digits=4, decimal_places=1)
    performance_rating = models.FloatField(default=0)
    efficiency_rating = models.FloatField(default=0)
    net_rating = models.FloatField(default=0)
    performance_rating_percentile = models.FloatField(default=0)
    efficiency_rating_percentile = models.FloatField(default=0)
    net_rating_percentile = models.FloatField(default=0)
    war_last_year = models.FloatField(default=0)
    war_year_before_last = models.FloatField(default=0)
    predicted_war = models.FloatField(default=0)
