services:
  - type: web
    name: django-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn playercards.wsgi:application --workers 4 --threads 4 --worker-class=gthread --log-file -
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cards_i9hy  # replace with your actual database name if different
          property: connectionString
    healthCheckPath: /api/health-check  # ensure this is a valid path
